### ISSUE TITLE
same code, but execute Transaction fail

### ISSUE THREAD

**Issue by ysykzheng** [klaytn/caver-java#140]
hello
my project work two env: prod, dev

before I issue this: https://github.com/klaytn/caver-java/issues/134
that is dev env.

yesterday, we publish same code to prod env. but execute Transaction fail.
 
prod env address:
https://scope.klaytn.com/account/0x506E1da423F51F160E5A7d1e62dF52C2F3F3f0A8?tabId=txList

first. I think, diff is not execute AccountUpdateTransaction.

so, do AccountUpdateTransaction with AccountKeyPublic.

but get below error.

String rawTransaction = "0xf8ac458505d21dba00830186a094a01efa8e7d3014a920f21487d7662db2800d031280b844a9059cbb00000000000000000000000080f4009fb84eb6a151565657fb272bb9f016efb6000000000000000000000000000000000000000000000000000000746a528800824055a0487c471f388d3f6d97f71e393a5790e106a6356defdb664e5849a95b32473deaa026ec7a537a2320e93fc73f0648bd555243cf871613f4b91dc75026c2b99f9f31";

String rawTransaction = "0xf8ac438505d21dba00830186a094a01efa8e7d3014a920f21487d7662db2800d031280b844a9059cbb000000000000000000000000e0711069b41397827fdfc3f31c901018e4301500000000000000000000000000000000000000000000000000000000746a528800824056a0076b0e1ed07104a1517fc0fa327753b49a8e188ca93f7b6cb64f40dba349366ea009e9e1e00255d0b0fd98ce0ee9ddfde129bffc8a45f93a45d49322efb5d0f1f7";

String rawTransaction = "0xf8ac458505d21dba00830186a094a01efa8e7d3014a920f21487d7662db2800d031280b844a9059cbb00000000000000000000000080f4009fb84eb6a151565657fb272bb9f016efb6000000000000000000000000000000000000000000000000000000746a528800824055a0487c471f388d3f6d97f71e393a5790e106a6356defdb664e5849a95b32473deaa026ec7a537a2320e93fc73f0648bd555243cf871613f4b91dc75026c2b99f9f31";

return error info:
```
-32000
a legacy transaction must be with a legacy account key
null
```

I try do AccountUpdateTransaction with AccountKeyLegacy

execute three rawTransaction, then getTransactionByHash, but get none data. 

please help.

**Comment by sirano11** [comment]
Your [last transaction](https://scope.klaytn.com/tx/0xad412e4e58a56f07968eee39871a4db2491015ff1d00a46fcb2fc99e8df52541?tabId=internalTx) is AccountUpdate to change AccountKeyLegacyType.

If you change your account key type to AccountKeyLegacy, "a legacy transaction must be with a legacy account key" error cannot occur.

Please explain more. When and how did you get this error.

And your three rawTransaction has some strange parts.
Your last transaction's nonce is 49. But your raw Transaction's nonce has 69, 67, 69. 
Why nonce does not increase sequentially?

**Comment by ysykzheng** [comment]
Due to the failure to send the transaction in the formal environment, I guess it may be that the transaction failed because AccountUpdate was not executed.

But after executing AccountUpdate AccountKeyPublic, the error `a legacy transaction must be with a legacy account key`

Then, I execute AccountUpdate AccountKeyLegacy, and then send the transaction, the above error will not appear.

For the nonce error you mentioned, I use the TransactionManager to manage it directly. This class will automatically set the nonce when signing.

```
public KlayRawTransaction sign(TransactionTransformer transactionTransformer) {
    KlayRawTransaction result = null;

    try {
      KlayCredentials credentials = this.walletManager.findByAddress(transactionTransformer.getFrom());
      if (transactionTransformer.getNonce() == null) {
        transactionTransformer.nonce(this.getNonceProcessor.getNonce(credentials));
      }

      result = transactionTransformer.build().sign(credentials, this.chainId);
    } catch (CredentialNotFoundException | IOException | EmptyNonceException | UnsupportedTxTypeException var4) {
      this.exception(var4);
    }

    return result;
  }
```

**Comment by ysykzheng** [comment]
I found another problem
With the same code, sending a transaction on our rpc server will fail, but using https://api.cypress.klaytn.net:8651/, sending a transaction will report an error.

String rawTransaction = "0x08f87f288505d21dba00830186a094e0711069b41397827fdfc3f31c901018e4301500019480f4009fb84eb6a151565657fb272bb9f016efb6f847f845824056a0a58ba13fe2cbee3bf962ef00da09bbffb6e427d3147f24555e30ba6eb9887d2aa0143a54e212933da3e38825a46bbd22359e206bc97363031199f80c96bec4b4c7";

```
-32000
nonce too low
```

But I checked, our klaytn wallet server, the synchronization status is normal.

**Comment by ysykzheng** [comment]
The third question is:
The transaction sent from the rpc server in our test environment will be displayed as Legacy Transaction, and the transaction sent from my local computer (using rpc is https://api.cypress.klaytn.net:8651/) will display Value Transfer.

https://scope.klaytn.com/tx/0xdfb9fa43a642ca5dd4fa0431372adba18e015c95c6ead09f7e61e831a9695dd4?tabId=internalTx

https://scope.klaytn.com/tx/0xcf582af3f9a325ae3e6987487eecc0c84f025a662115c55faa89eafcaf5a2640?tabId=internalTx

**Comment by sirano11** [comment]
Aren't you setting TransactionType as valueTransfer and sending it through your local computer?

### First Transaction receipt. - 0xdfb9fa43a642ca5dd4fa0431372adba18e015c95c6ead09f7e61e831a9695dd4
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "blockHash": "0xf936229a25a51cfb00e09d57dadb24d78e95e65ba44345e9e4df95fe52ca4f0c",
    "blockNumber": "0x1f2c7ef",
    "from": "0x6b683c2355e738af2bc0b3a456bfff0d6c1fbaf2",
    "gas": "0x5208",
    "gasPrice": "0x5d21dba00",
    "gasUsed": "0x5208",
    "input": "0x",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0xa",
    "senderTxHash": "0xdfb9fa43a642ca5dd4fa0431372adba18e015c95c6ead09f7e61e831a9695dd4",
    "signatures": [
      {
        "V": "0x4055",
        "R": "0xab50dbc29ed4e0926f3680ea3168fb1e3cd68b9381fa4d7a18bce6b7c9d9c002",
        "S": "0x39c54ea2f31f233c31e4f47843b09d42757d53976f6e76ea1b167da8bffd7bfb"
      }
    ],
    "status": "0x1",
    "to": "0xe0711069b41397827fdfc3f31c901018e4301500",
    "transactionHash": "0xdfb9fa43a642ca5dd4fa0431372adba18e015c95c6ead09f7e61e831a9695dd4",
    "transactionIndex": "0x3",
    "type": "TxTypeLegacyTransaction",
    "typeInt": 0,
    "value": "0x25c2793687e00"
  }
}

Second Transaction receipt - 0xcf582af3f9a325ae3e6987487eecc0c84f025a662115c55faa89eafcaf5a2640

{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "blockHash": "0xf44046b22925a5f6a2939bd393f95fded37b9ff47e576b0adb6169022ea91dc1",
    "blockNumber": "0x1f41194",
    "from": "0x80f4009fb84eb6a151565657fb272bb9f016efb6",
    "gas": "0x186a0",
    "gasPrice": "0x5d21dba00",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x27",
    "senderTxHash": "0xcf582af3f9a325ae3e6987487eecc0c84f025a662115c55faa89eafcaf5a2640",
    "signatures": [
      {
        "V": "0x4056",
        "R": "0xbdb407daae1ff17a582f4e66ff6b12cb9d521daf6894446e5b0a1f1ad5e2fc1f",
        "S": "0x76197845f4e99503cc7a4f1964c4d2f99fc545874e7f9d62fe3092efb1774eb6"
      }
    ],
    "status": "0x1",
    "to": "0xe0711069b41397827fdfc3f31c901018e4301500",
    "transactionHash": "0xcf582af3f9a325ae3e6987487eecc0c84f025a662115c55faa89eafcaf5a2640",
    "transactionIndex": "0x0",
    "type": "TxTypeValueTransfer",
    "typeInt": 8,
    "value": "0x1"
  }
}

**Comment by ysykzheng** [comment]
my code is same this:
```
ValueTransferTransaction valueTransferTransaction = ValueTransferTransaction.create(
        credentials.getAddress(),  // fromAddress
        "0xE0711069B41397827fdfc3f31C901018e4301500",  // toAddress
        Convert.toPeb(BigDecimal.ONE, Convert.Unit.PEB).toBigInteger(),  // value
        BigInteger.valueOf(100_000)  // gasLimit
    );

KlayRawTransaction klayRawTransaction = transactionManager.sign(valueTransferTransaction);
String rawTransaction = klayRawTransaction.getValueAsString();
```

so, I think the wallet server is error.

**Comment by ysykzheng** [comment]
I found some error codes and I am trying to fix them.
For the time being, this issue need not be followed or closed.
If the follow-up question does not exist, I will close it.

**Comment by sirano11** [comment]
ok, thank you!

**Comment by ysykzheng** [comment]
please help, the transaction why fail

https://scope.klaytn.com/tx/0x000ebb82da513ba08e99bc434a6b2c716cdbe8debc6c50be212a37b511f50d9b?tabId=internalTx
https://scope.klaytn.com/tx/0x6e9b6105af1d1171b2af4ee60b9847b01112c2d556be974cb76e5f5ace6afd5f?tabId=internalTx

**Comment by sirano11** [comment]
This error occurs while executing SmartContract. Please refer to [Transaction Error](https://docs.klaytn.com/bapp/json-rpc/transaction-error-codes)
And if you are running to EN, please refer to [debug_traceTransaction](https://docs.klaytn.com/bapp/json-rpc/api-references/debug/tracing#debug_tracetransaction). 
This API does not available "https://api.cypress.klaytn.net:8651"
