### ISSUE TITLE
TxTypeLegacyTransaction

### ISSUE THREAD

**Issue by swq123** [klaytn/caver-java#142]
request

{"method":"klay_sendRawTransaction","id":1,"jsonrpc":"2.0","params":["0xf86e808504a817c80082ea6094958e2e083d6a16799e4d588015153ee429508d4f880de0b6b3a7640000808207f5a08638176342e6b99bc93d1dbda15aa5572e68e87b198efb68b8559ec24363f3d0a06b173d8f4ac24f50420d9a4b6f4cbb2f571883e00eb0b5343bb9b2ae9f5492eb"]}

response:
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"invalid unit price"}}

RPC:https://api.baobab.klaytn.net:8651

**Comment by sirano11** [comment]
Please provide more information about the development environment.

If you want to send a KLAY, you must set gas price 25ston.
https://docs.klaytn.com/bapp/sdk/caver-js/v1.4.1#caution-when-sending-a-transaction-to-klaytn

**Comment by sirano11** [comment]
@swq123 
If there are no other issues, this will be closed.

**Comment by machine-creek** [comment]
I had the same problem and asked for help.

This is the parameter
 gas price 25000000000
 limit 21000
 chainId 8217
request

{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "klay_sendRawTransaction",
    "params": [
        "0x08f885238505d21dba00825208940282c0f32b1816dfdb0ba60059a4f25109a73fc1872386f26fc1000094d73d9aa55abbd6cfbed3e9ad7f8be2f6d83c70dcf847f845824056a087fc7935f42ff1ea908960cb7175a768ccb3f77b219cd913ca8038a9f4deabc2a023d1183bca467003397c7c71f4336de09397c444684d39afe78a01753d3fae5a"
    ]
}

response:
{
    "jsonrpc": "2.0",
    "id": "1",
    "error": {
        "code": -32000,
        "message": "invalid unit price"
    }
}

RPC:https://api.baobab.klaytn.net:8651/
