### ISSUE TITLE
1.5.5 caver-java release doesn't have jar zip file.

### ISSUE THREAD

**Issue by benjioh5** [klaytn/caver-java#188]
I'm patching on https://github.com/klaytn/homebrew-klaytn 's out of dated formula. When I bump up the release v1.3.1 to v1.5.5, I cannot find adjust jar zip file for homebrew formula distribution.

At [documentation](https://github.com/klaytn/caver-java#command-line-tool), jar distribution and homebrew formula might be distributed with release. Could you check this?

**Comment by sirano11** [comment]
Hi, @benjioh5 

caver-java console registered in homebrew supports API of version 1.4 or lower and
there is no plan to update the console program that supports API of version 1.5.0 or higher to which "KIP-34: Klaytn SDK Common Architecture" is applied.

**Comment by kjhman21** [comment]
Hi, @benjioh5 
In addition to the @sirano11 's comment, we developed a dynamic ABI loader.
If you use the dynamic ABI loader, you don't need to use CLI anymore to make a class for your contract.

Please refer to https://medium.com/klaytn/caver-java-dynamic-abi-loader-8ccef10e7e68 .
This article is written in Korean.

**Comment by benjioh5** [comment]
@sirano11 @kjhman21 I see, so I just left homebrew Formul's caver-java version to v1.3.1. Thanks!
