### ISSUE TITLE
How to call the contract for transfer

### ISSUE THREAD

**Issue by 90hacker** [klaytn/caver-java#195]
I created a coin myself。
How do I transfer coins to another address。
Best to provide a Java demo。

I am constructing a `LegacyTransaction or SmartContractExecution` object but I did not find the parameters of the contract address

**Comment by sirano11** [comment]
The answer was too late. I'm sorry.

If you created the coins(tokens?) yourself, you would have deployed the Contract yourself. 
You can find the Contract address by looking at the "contractAddress" in the Transaction receipt of the Transaction used for Contract deploy.

or

You can easily deploy and transfer token(FT) using KIP7 class.

```java
public String CONTRACT_NAME = "TEST";
public String CONTRACT_SYMBOL = "SYMT";
public int CONTRACT_DECIMALS = 18;
public BigInteger CONTRACT_INITIAL_SUPPLY = BigInteger.valueOf(100_000).multiply(BigInteger.TEN.pow(CONTRACT_DECIMALS)); // 100000 * 10^18


Caver caver = new Caver("EN server URL");
SingleKeyring keyring = (SingleKeyring)caver.wallet.add(KeyringFactory.createFromPrivateKey(0x{your private Key}));
SendOptions sendOptions = new SendOptions(keyring.getAddress());

//----> deploy KIP7(FT) contract
KIP7DeployParams kip7DeployParam = new KIP7DeployParams(CONTRACT_NAME, CONTRACT_SYMBOL, CONTRACT_DECIMALS, CONTRACT_INITIAL_SUPPLY);
KIP7 kip7contract = KIP7.deploy(caver, kip7DeployParam, keyring.getAddress());
System.out.println(kip7contract.getContractAddress());

//----> Transfer token
BigInteger transferAmount = BigInteger.TEN.multiply(BigInteger.TEN.pow(CONTRACT_DECIMALS)); // 10 * 10^18
TransactionReceipt.TransactionReceiptData receiptData = kip7contract.transfer(0x{recipient address}, transferAmount, sendOptions);

if(!receiptData.getStatus().equals("0x1")) {
   // Handling error
}
```

**Comment by 90hacker** [comment]
I have deployed my contract on the blockchain.
I changed how to construct `KIP7 kip7contract` object。

**Comment by sirano11** [comment]
If the contract you deployed satisfies the specifications of ERC-20 or KIP-7, that code will work.

**Comment by 90hacker** [comment]
Thank you。
