### ISSUE TITLE
TxTypeValuetransfer error！

### ISSUE THREAD

**Issue by AlleniCode** [klaytn/caver-java#20]
I made a TxTypeValuetransfer myself, but the api sendRawTransaction called failed, could you help me? Thx!

curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"klay_sendRawTransaction","params":[08f87c80853a35294400830186a094f90675a56a03f836204d66c0f923e00500ddc90a019451f5b8c864ce3b09a353459f95cf7bf9f840b9e8808207f5a096e433eded5c10c504d9c120bd9655ae327e2c94023ce07637d932a9e7f7980ba063c783c47ece9d77d1f6a9e3181ebe0a210b52ccf98759dc07d9e7d94c521e30],"id":1}' https://api.baobab.klaytn.net:8651

{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character '8' after array element"}}

**Comment by nogang** [comment]
@AlleniCode  From the encoded value, the `from` address is correct, but the signature is strange. If you want to create an encoded value and check it, compare it with the raw transaction value that is signed by caver-java.
