### ISSUE TITLE
Expose javadoc comments of private fields to the getter and setter method

### ISSUE THREAD

**Issue by majecty** [klaytn/caver-java#208]
There are JavaDoc comments on the private fields in the `TransactionData` type.

https://github.com/klaytn/caver-java/blob/dev/core/src/main/java/com/klaytn/caver/methods/response/Transaction.java#L37

But the official JavaDoc site of caver-java does not show the information: https://javadoc.io/doc/com.klaytn.caver/core/latest/com/klaytn/caver/methods/response/Transaction.TransactionData.html

Also, IDEs like IntelliJ show the document of getter or setter when using the functions in code.
However, it does not show the doc in the private fields.

The comments in the private fields will help programmers significantly.
If we expose the docs more programmer-friendly, many programmers will be happier.

**Comment by sirano11** [comment]
Thanks for your opinion. I will consider it.
