### ISSUE TITLE
Can I make a keystoreJson in caver-java to use in caver-js

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-java#66]
I want to send encrypted privateKey to javascript use

Can I make a encrypt privateKey and make keystoreJson in caver-java to use in caver-js
- https://ko.docs.klaytn.com/bapp/sdk/caver-js/api-references/caver.klay.accounts#decrypt

If then what method should I use

**Comment by kjhman21** [comment]
Thanks for filing this issue!

Please check out this function:
https://github.com/klaytn/caver-java/blob/17f4f13170ffee123bb6cc19ad249ce6655c250b/core/src/test/java/com/klaytn/caver/feature/WalletTest.java#L113

**Comment by skqksh** [comment]
So.. walletFile of caver-java is like as keystoreJson of caver-js

Thank you so much
