### ISSUE TITLE
Implementation of KCT (Fungible/Non Fungible token in Klaytn)

### ISSUE THREAD

**Issue by sirano11** [klaytn/caver-java#82]
**Is your request related to a problem? Please describe.**
Implementation to easily use Fungible / Non Fungible tokens in Klaytn

**Describe the solution you'd like**
Implement new classes to handle Fungible / Non Fungible tokens

**Describe alternatives you've considered**

**Additional context**

**Comment by jimni1222** [comment]
@sirano11 
The implementation for KIP-7 and KIP-17 token contracts has been completed and merged into the dev branch, so i will close this issue. 

Thank you for your hard work. :)
